### ISSUE TITLE
missing folder

### ISSUE THREAD

**Issue by zjjj** [NAACL2018Anonymous/submission#2]
Thanks for sharing this project. However, I noticed an issue with a missing folder. 
As introduced in README, there should be the following folder in the repo but I could not find it:
"kbembeddings: code forked and adapted from https://github.com/thunlp/KB2E"

**Comment by hadyelsahar** [comment]
Hello, sorry for the confusing. 
I am preparing the code for the camera ready I am making a new version of the whole repo atm again.

**Comment by hadyelsahar** [comment]
This code is made mainly to train TransE word embeddings yourself. Currently not in use since I will download the pretrained KB embeddings in the repo and will make them available through a downloadscript. 

Until then, the current version of the code doesn't rely on pretrained KB embeddings. In the config file:
`self.USE_PRETRAINED_KB_EMBEDDINGS = False` 

Sorry for the confusing. I am preparing the code for the camera ready I am making a new version of the whole repo atm again.

**Comment by zjjj** [comment]
Thanks much for the quick response! 
I noticed that script "prepare_repo.sh" have been added and folder "./kbembeddings" have been included. Looking forward to the new version of the repo.

**Comment by hadyelsahar** [comment]
sure now you can add 
 self.USE_PRETRAINED_KB_EMBEDDINGS =True 

And start training with pretrained KB embeddings as well. 
Pretrained word embeddings are on the way.
